---
- fail: msg="Please configure {{inventory_hostname}} in ff_supernodes"
  when: ff_supernodes[inventory_hostname]|default(false) == false

- name: Install tinc
  apt: name=tinc

- file: path=/etc/tinc/backbone state=directory owner=root group=root
- name: Enable backbone
  lineinfile: dest=/etc/tinc/nets.boot line=backbone

- command: /usr/sbin/tincd -n backbone -K 4096
  args:
    creates: /etc/tinc/backbone/rsa_key.priv

- name: tinc.conf
  template: src=tinc.conf.j2 dest='/etc/tinc/backbone/tinc.conf' owner=root group=root mode='0644'
  notify:
  - restart tinc
- name: tinc-up
  template: src=tinc-up.j2   dest='/etc/tinc/backbone/tinc-up'   owner=root group=root mode='0744'
  notify:
  - restart tinc

- name: create tinc subnet defs
  template: src=tinc_subnet.j2 dest='/etc/tinc/backbone/subnet'
  notify:
  - restart tinc

- name: concat subnet defs and pubkey
  shell: "/bin/cat /etc/tinc/backbone/subnet /etc/tinc/backbone/rsa_key.pub > /etc/tinc/backbone/{{ inventory_hostname }}" 
  args:
    creates: "/etc/tinc/backbone/{{ inventory_hostname }}"

- git: repo="https://github.com/ff-kbu/bbkeys.git" dest='/etc/tinc/backbone/hosts'
  notify:
  - restart tinc

- service: name=tinc state=started pattern="/usr/sbin/tincd -n backbone"
