---
- name: Add repository for fastd and batman-adv
  apt_key: keyserver='pgp.surfnet.nl' id=6664E7BDA6B669881EC52E7516EF3F64CB201D9C
- apt_repository: repo='deb http://repo.universe-factory.net/debian/ sid main'
- apt_repository: repo='deb-src http://repo.universe-factory.net/debian/ sid main' update_cache=yes

- name: Add wheezy backports for libjson-c2
  apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main'
  when: ansible_distribution_release == "wheezy"
