---
- name: Install git
  apt: name=git state=present

- name: Create peers directory
  file: dest="/etc/fastd/{{ fastd_interface }}/peers" state=directory

- name: Upload on-up hook
  template: src=on-up.j2 dest="/etc/fastd/{{ fastd_interface }}/on-up" owner=root group=root mode='0755'

- name: Remove deprecated hook
  file: path="/etc/fastd/{{ fastd_interface }}/fastd-up" state=absent

- name: Clone fastd pubkeys
  git: repo={{fastd_pubkeys_repo}} dest="/etc/fastd/{{ fastd_interface }}/backbone" version={{fastd_pubkeys_repo_version}}
