---
- name: sysctl config
  sysctl: name={{ item.key }} value={{ item.value }} state=present sysctl_set=yes
  with_dict:
    "net.ipv4.ip_forward": 1
    "net.ipv4.ip_no_pmtu_disc": 1
    "net.ipv6.conf.all.forwarding": 1
    "net.ipv6.conf.all.autoconf": 0
    "net.ipv6.conf.all.accept_ra": 0
    "net.core.rmem_max": 83886080
    "net.core.wmem_max": 83886080
    "net.core.rmem_default": 83886080
    "net.core.wmem_default": 83886080

- name: Assign name to routing table
  lineinfile: dest="/etc/iproute2/rt_tables" regexp="^200" line="200 freifunk"

- name: Install rsyslog
  apt: name=rsyslog state=present

- name: rsyslog file for fastd
  copy: src=etc/rsyslog.d/fastd.conf dest=/etc/rsyslog.d/fastd.conf owner=root group=root mode='0644'
  notify:
  - restart rsyslog

- name: rsyslog file for dhcpd
  copy: src=etc/rsyslog.d/dhcpd.conf dest=/etc/rsyslog.d/dhcpd.conf owner=root group=root mode='0644'
  notify:
  - restart rsyslog

