---
- name: sysctl config
  sysctl: name={{ item.key }} value={{ item.value }} state=present sysctl_set=yes
  with_dict:
    "net.ipv4.ip_forward": 1
    "net.ipv4.ip_no_pmtu_disc": 1
    "net.ipv6.conf.all.forwarding": 1
    "net.ipv6.conf.all.autoconf": 0
    "net.ipv6.conf.all.accept_ra": 0
    "net.core.rmem_max": 83886080
    "net.core.wmem_max": 83886080
    "net.core.rmem_default": 83886080
    "net.core.wmem_default": 83886080

- name: Assign name to routing table
  lineinfile: dest="/etc/iproute2/rt_tables" regexp="^200" line="200 freifunk"

- name: Install rsyslog
  apt: name=rsyslog state=present

- name: copy rsyslog files
  copy: src='etc/rsyslog.d/{{ item }}' dest='/etc/rsyslog.d/{{ item }}' owner=root group=root mode='0644'
  with_items:
  - fastd.conf
  - dhcpd.conf
  notify:
  - restart rsyslog

- name: copy logrotate files
  copy: src='etc/logrotate.d/{{ item }}' dest='/etc/logrotate.d/{{ item }}' owner=root group=root mode='0644'
  with_items:
  - fastd
  - dhcpd

- name: copy logrotate hourly script
  copy: src='etc/cron.hourly/logrotate' dest='/etc/cron.hourly/logrotate' owner=root group=root mode='0744'
