---

- name: install nagios-nrpe-server, python3-pip
  apt: name={{ item }} state=present
  with_items:
    - nagios-nrpe-server
    - python3-pip

- name: make sure debinan supplied netaddr is not installed
  apt: name=python3-netaddr state=absent

- name: install nagiosplugin, netaddr from pip3
  pip: executable=/usr/bin/pip-3.2 name={{ item }} state=latest
  with_items:
    - nagiosplugin
    - netaddr

- name: nrpe.cfg
  template: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg owner=root group=root mode='0644'
  notify:
    - restart nrpe

- name: nrpe_local.cfg
  copy: src=nrpe_local.cfg dest=/etc/nagios/nrpe_local.cfg owner=root group=root mode='0644'
  notify:
    - restart nrpe

- name: check_dhcpd_usage
  copy: src=check_dhcpd_usage dest=/usr/local/bin/check_dhcpd_usage owner=root group=root mode='0755'

- service: name='nagios-nrpe-server' state=started
