---
# tasks file for batman-adv-15

- name: Add wheezy backports for batman compat 15
  apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main'
  when: ansible_distribution_release == "wheezy"

- name: remove batman-adv compat 14
  apt: name=batman-adv-dkms state=absent

- name: install batman-adv compat 15 via backports kernel
  apt: name=linux-image-amd64 state=latest default_release=wheezy-backports update_cache=yes
  when: ansible_distribution_release == "wheezy"

- name: install batctl
  apt: name=batctl state=present install_recommends=false

- name: Enable batman during boot
  lineinfile: dest=/etc/modules line=batman-adv
- modprobe: name=batman-adv
